version: "3.8"

services:
  qa-buddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qa-buddy-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_FILE_NAME=/app/data/database.sqlite
    volumes:
      # Persist database and uploads
      - qa-buddy-data:/app/data
      - qa-buddy-uploads:/app/public/uploads
      # Mount dictionaries as read-only (optional - for custom dictionary persistence)
      - ./public/dictionaries:/app/public/dictionaries:ro
    restart: unless-stopped
    healthcheck:
      test: [CMD, wget, --no-verbose, --tries=1, --spider, "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qa-buddy-network

volumes:
  qa-buddy-data:
    driver: local
  qa-buddy-uploads:
    driver: local

networks:
  qa-buddy-network:
    driver: bridge
